### ISSUE TITLE
Please update ReadMe

### ISSUE THREAD

**Issue by djmtype** [rebelchris/astropress#1]
Please update the ReadMe to reflect this project. 

There's a couple things worth noting otherwise Astro will fail at returning any content. Check out `./src/lib/api.js` for the nodes this project queries for. 

Obviously, you'll need a WP GraphQL client installed like [WPGraphQL](https://www.wpgraphql.com/). 

Be sure to have at least one published Wordpress Page. 
Out of the box Wordpress automatically installs "Sample" Page. However, it might not install any content when using the WP CLI.  

Be sure to set up a menu within Wordpress and assign as "Primary menu". Add at least one menu item. Failing to do so will result in `TypeError: Cannot destructure property 'menuItems' of '(intermediate value)' as it is undefined.`

**Comment by rebelchris** [comment]
@djmtype thanks for this feedback, I'll add it to me list and refactor it to link to the article with these details.

**Comment by rebelchris** [comment]
@djmtype Hi, I've updated the readme linking to the original article.
Let me know if that helps.
